spring.application.name=supermarket-api

# SERVER
server.port=${SERVER_PORT:8080}
spring.profiles.active=${SPRING_PROFILES_ACTIVE:default}
server.forward-headers-strategy=framework
server.tomcat.remoteip.remote-ip-header=x-forwarded-for
server.tomcat.remoteip.protocol-header=x-forwarded-proto

# PRODUCTION
prod.admin.username=${PROD_ADMIN_USERNAME:sysadmin}
prod.admin.password=${PROD_ADMIN_PASSWORD:sysadmin123}
prod.admin.email=${PROD_ADMIN_EMAIL:sysadmin@supermarket.com}

# DATASOURCE
spring.datasource.url=jdbc:h2:mem:supermarket-db
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# LOGGING
logging.level.com.massemiso.supermarket_api=INFO
logging.level.org.hibernate=INFO
logging.file.name=${LOGGING_FILE_NAME:./logs/api/spring.log}

# JWT
security.jwt.key.private=${JWT_SECRET:f043c350d733e63ffb7d66987f0a5577f896077c64b400324541ebd60befa888}
security.jwt.user.generator=${JWT_USER_GENERATOR:AUTH0-JWT-BACKEND}
security.jwt.token.time=${JWT_EXPIRATION:3600000}

# SWAGGER UI
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha
springdoc.cache.disabled=true