spring.application.name=supermarket-api

spring.datasource.url=jdbc:h2:mem:supermarket-db
#spring.h2.console.enabled=true
#spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# LOGGING
logging.level.root=INFO
logging.level.com.massemiso.supermarket=DEBUG
logging.level.org.hibernate.SQL=INFO
#logging.file.path=logs/
