spring.application.name=supermarket-api

# DATASOURCE
spring.datasource.url=jdbc:h2:mem:supermarket-db
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# LOGGING
logging.level.root=INFO
logging.level.org.hibernate.SQL=INFO
