user.admin.username=admin
user.admin.password=admin123
user.admin.email=admin@supermarket.com
user.manager.username=manager
user.manager.password=manager123
user.manager.email=manager@supermarket.com
user.cashier.username=cashier
user.cashier.password=cashier123
user.cashier.email=cashier@supermarket.com
user.guest.username=guest
user.guest.password=guest123
user.guest.email=guest@supermarket.com
